export enum ErrorCodes {
  INTERNAL_SERVER_ERROR = 'API-PM-500',
  COLLECTION_NOT_FOUND = 'API-PM-1',

  // ACCOUNT MONGO
  MONGO_SEARCH_ACCOUNTS_FAILED = 'API-PM-100',
  MONGO_CREATE_ACCOUNT_FAILED = 'API-PM-101',
  MONGO_UPDATE_ACCOUNT_FAILED = 'API-PM-102',
  MONGO_CHECK_ACCOUNT_EXISTED_FAILED = 'API-PM-103',

  // ACCOUNT SERVICE
  SERVICE_SEARCH_ACCOUNTS_FAILED = 'API-PM-200',
  SERVICE_CREATE_ACCOUNT_FAILED = 'API-PM-201',
  SERVICE_UPDATE_ACCOUNT_FAILED = 'API-PM-202',
  SERVICE_ACCOUNT_NOT_EXISTED = 'API-PM-203',
  SERVICE_DELETE_ACCOUNT_FAILED = 'API-PM-204',

  // PORTFOLIO MONGO
  MONGO_SEARCH_POSITIONS_FAILED = 'API-PM-300',
  MONGO_CREATE_POSITION_FAILED = 'API-PM-301',
  MONGO_UPDATE_POSITION_FAILED = 'API-PM-302',
  MONGO_CHECK_POSITION_EXISTED_FAILED = 'API-PM-303',

  // PORTFOLIO SERVICE
  SERVICE_SEARCH_POSITIONS_FAILED = 'API-PM-400',
  SERVICE_CREATE_POSITION_FAILED = 'API-PM-401',
  SERVICE_UPDATE_POSITION_FAILED = 'API-PM-402',
  SERVICE_POSITION_EXISTED = 'API-PM-403',
  SERVICE_POSITION_NOT_EXISTED = 'API-PM-404',
  SERVICE_DELETE_POSITION_FAILED = 'API-PM-405'
}

export enum ErrorMessages {
  COLLECTION_NOT_FOUND = 'collection not found',

  // ACCOUNT SERVICE
  SERVICE_ACCOUNT_NOT_EXISTED = 'account does not exist',

  // PORTFOLIO SERVICE
  SERVICE_POSITION_EXISTED = 'position has already existed',
  SERVICE_POSITION_NOT_EXISTED = 'position does not exist'
}
