export enum ErrorCodes {
  INTERNAL_SERVER_ERROR = 'API-PM-500',
  COLLECTION_NOT_FOUND = 'API-PM-1',
  MONGO_SEARCH_ACCOUNTS_FAILED = 'API-PM-2',
  MONGO_CREATE_ACCOUNT_FAILED = 'API-PM-3',
  MONGO_UPDATE_ACCOUNT_FAILED = 'API-PM-4',
  MONGO_SEARCH_PORTFOLIOS_FAILED = 'API-PM-5',
  MONGO_CREATE_PORTFOLIO_FAILED = 'API-PM-6',
  MONGO_UPDATE_PORTFOLIO_FAILED = 'API-PM-7',
  MONGO_CHECK_PORTFOLIO_EXISTED_FAILED = 'API-PM-8',
  SERVICE_PORTFOLIO_EXISTED = 'API-PM-9',
  SERVICE_SEARCH_PORTFOLIOS_FAILED = 'API-PM-10',
  SERVICE_CREATE_PORTFOLIO_FAILED = 'API-PM-11',
  SERVICE_UPDATE_PORTFOLIO_FAILED = 'API-PM-12',
  SERVICE_SEARCH_ACCOUNTS_FAILED = 'API-PM-13',
  SERVICE_CREATE_ACCOUNT_FAILED = 'API-PM-14',
  SERVICE_UPDATE_ACCOUNT_FAILED = 'API-PM-15',
  SERVICE_PORTFOLIO_NOT_EXISTED = 'API-PM-16'
}

export enum ErrorMessages {
  COLLECTION_NOT_FOUND = 'collection not found',
  SERVICE_PORTFOLIO_EXISTED = 'portfolio has already existed',

  SERVICE_PORTFOLIO_NOT_EXISTED = 'portfolio does not exist'
}
