export enum ErrorCodes {
  INTERNAL_SERVER_ERROR = 'API-PM-500',
  COLLECTION_NOT_FOUND = 'API-PM-1',

  // ACCOUNT MONGO
  MONGO_SEARCH_ACCOUNTS_FAILED = 'API-PM-100',
  MONGO_CREATE_ACCOUNT_FAILED = 'API-PM-101',
  MONGO_UPDATE_ACCOUNT_FAILED = 'API-PM-102',
  MONGO_CHECK_ACCOUNT_EXISTED_FAILED = 'API-PM-103',

  // ACCOUNT SERVICE
  SERVICE_SEARCH_ACCOUNTS_FAILED = 'API-PM-200',
  SERVICE_CREATE_ACCOUNT_FAILED = 'API-PM-201',
  SERVICE_UPDATE_ACCOUNT_FAILED = 'API-PM-202',
  SERVICE_ACCOUNT_NOT_EXISTED = 'API-PM-203',

  // PORTFOLIO MONGO
  MONGO_SEARCH_PORTFOLIOS_FAILED = 'API-PM-300',
  MONGO_CREATE_PORTFOLIO_FAILED = 'API-PM-301',
  MONGO_UPDATE_PORTFOLIO_FAILED = 'API-PM-302',
  MONGO_CHECK_PORTFOLIO_EXISTED_FAILED = 'API-PM-303',

  // PORTFOLIO SERVICE
  SERVICE_SEARCH_PORTFOLIOS_FAILED = 'API-PM-400',
  SERVICE_CREATE_PORTFOLIO_FAILED = 'API-PM-401',
  SERVICE_UPDATE_PORTFOLIO_FAILED = 'API-PM-402',
  SERVICE_PORTFOLIO_EXISTED = 'API-PM-403',
  SERVICE_PORTFOLIO_NOT_EXISTED = 'API-PM-404'
}

export enum ErrorMessages {
  COLLECTION_NOT_FOUND = 'collection not found',

  // ACCOUNT SERVICE
  SERVICE_ACCOUNT_NOT_EXISTED = 'account does not exist',

  // PORTFOLIO SERVICE
  SERVICE_PORTFOLIO_EXISTED = 'portfolio has already existed',
  SERVICE_PORTFOLIO_NOT_EXISTED = 'portfolio does not exist'
}
